---
# Source: cert-manager-webhook-k8s-dns/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-webhook-k8s-dns
  namespace: default
  labels:
    app: cert-manager-webhook-k8s-dns
    chart: cert-manager-webhook-k8s-dns-0.1.0
    release: cert-manager-webhook-k8s-dns
    heritage: Helm
---
# Source: cert-manager-webhook-k8s-dns/templates/rbac.yaml
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cert-manager-webhook-k8s-dns:domain-solver
  labels:
    app: cert-manager-webhook-k8s-dns
    chart: cert-manager-webhook-k8s-dns-0.1.0
    release: cert-manager-webhook-k8s-dns
    heritage: Helm
rules:
  - apiGroups:
      - acme.dns.linka.cloud
    resources:
      - '*'
    verbs:
      - 'create'
---
# Source: cert-manager-webhook-k8s-dns/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-webhook-k8s-dns:dns-challenge-solver
  labels:
    app: cert-manager-webhook-k8s-dns
    chart: cert-manager-webhook-k8s-dns-0.1.0
    release: cert-manager-webhook-k8s-dns
    heritage: Helm
rules:
- apiGroups:
  - dns.linka.cloud
  resources:
  - dnsrecord
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
# Source: cert-manager-webhook-k8s-dns/templates/rbac.yaml
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-k8s-dns:auth-delegator
  labels:
    app: cert-manager-webhook-k8s-dns
    chart: cert-manager-webhook-k8s-dns-0.1.0
    release: cert-manager-webhook-k8s-dns
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-k8s-dns
    namespace: default
---
# Source: cert-manager-webhook-k8s-dns/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-k8s-dns:domain-solver
  labels:
    app: cert-manager-webhook-k8s-dns
    chart: cert-manager-webhook-k8s-dns-0.1.0
    release: cert-manager-webhook-k8s-dns
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook-k8s-dns:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
---
# Source: cert-manager-webhook-k8s-dns/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-k8s-dns:dns-challenge-solver
  labels:
    app: cert-manager-webhook-k8s-dns
    chart: cert-manager-webhook-k8s-dns-0.1.0
    release: cert-manager-webhook-k8s-dns
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook-k8s-dns:dns-challenge-solver
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: cert-manager-webhook-k8s-dns
  namespace: cert-manager
---
# Source: cert-manager-webhook-k8s-dns/templates/rbac.yaml
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-k8s-dns:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: cert-manager-webhook-k8s-dns
    chart: cert-manager-webhook-k8s-dns-0.1.0
    release: cert-manager-webhook-k8s-dns
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-k8s-dns
    namespace: default
---
# Source: cert-manager-webhook-k8s-dns/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook-k8s-dns
  namespace: default
  labels:
    app: cert-manager-webhook-k8s-dns
    chart: cert-manager-webhook-k8s-dns-0.1.0
    release: cert-manager-webhook-k8s-dns
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: cert-manager-webhook-k8s-dns
    release: cert-manager-webhook-k8s-dns
---
# Source: cert-manager-webhook-k8s-dns/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook-k8s-dns
  namespace: default
  labels:
    app: cert-manager-webhook-k8s-dns
    chart: cert-manager-webhook-k8s-dns-0.1.0
    release: cert-manager-webhook-k8s-dns
    heritage: Helm
spec:
  replicas: 
  selector:
    matchLabels:
      app: cert-manager-webhook-k8s-dns
      release: cert-manager-webhook-k8s-dns
  template:
    metadata:
      labels:
        app: cert-manager-webhook-k8s-dns
        release: cert-manager-webhook-k8s-dns
    spec:
      serviceAccountName: cert-manager-webhook-k8s-dns
      containers:
        - name: cert-manager-webhook-k8s-dns
          image: "linkacloud/cert-manager-webhook-k8s-dns:latest"
          imagePullPolicy: IfNotPresent
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          env:
            - name: GROUP_NAME
              value: "acme.dns.linka.cloud"
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          resources:
            {}
      volumes:
        - name: certs
          secret:
            secretName: cert-manager-webhook-k8s-dns-webhook-tls
---
# Source: cert-manager-webhook-k8s-dns/templates/apiservice.yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.acme.dns.linka.cloud
  labels:
    app: cert-manager-webhook-k8s-dns
    chart: cert-manager-webhook-k8s-dns-0.1.0
    release: cert-manager-webhook-k8s-dns
    heritage: Helm
  annotations:
    cert-manager.io/inject-ca-from: "default/cert-manager-webhook-k8s-dns-webhook-tls"
spec:
  group: acme.dns.linka.cloud
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: cert-manager-webhook-k8s-dns
    namespace: default
  version: v1alpha1
---
# Source: cert-manager-webhook-k8s-dns/templates/pki.yaml
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cert-manager-webhook-k8s-dns-ca
  namespace: "default"
  labels:
    app: cert-manager-webhook-k8s-dns
    chart: cert-manager-webhook-k8s-dns-0.1.0
    release: cert-manager-webhook-k8s-dns
    heritage: Helm
spec:
  secretName: cert-manager-webhook-k8s-dns-ca
  duration: 43800h # 5y
  issuerRef:
    name: cert-manager-webhook-k8s-dns-selfsign
  commonName: "ca.cert-manager-webhook-k8s-dns.cert-manager"
  isCA: true
---
# Source: cert-manager-webhook-k8s-dns/templates/pki.yaml
# Finally, generate a serving certificate for the webhook to use
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cert-manager-webhook-k8s-dns-webhook-tls
  namespace: "default"
  labels:
    app: cert-manager-webhook-k8s-dns
    chart: cert-manager-webhook-k8s-dns-0.1.0
    release: cert-manager-webhook-k8s-dns
    heritage: Helm
spec:
  secretName: cert-manager-webhook-k8s-dns-webhook-tls
  duration: 8760h # 1y
  issuerRef:
    name: cert-manager-webhook-k8s-dns-ca
  dnsNames:
  - cert-manager-webhook-k8s-dns
  - cert-manager-webhook-k8s-dns.default
  - cert-manager-webhook-k8s-dns.default.svc
---
# Source: cert-manager-webhook-k8s-dns/templates/pki.yaml
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: cert-manager-webhook-k8s-dns-selfsign
  namespace: "default"
  labels:
    app: cert-manager-webhook-k8s-dns
    chart: cert-manager-webhook-k8s-dns-0.1.0
    release: cert-manager-webhook-k8s-dns
    heritage: Helm
spec:
  selfSigned: {}
---
# Source: cert-manager-webhook-k8s-dns/templates/pki.yaml
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: cert-manager-webhook-k8s-dns-ca
  namespace: "default"
  labels:
    app: cert-manager-webhook-k8s-dns
    chart: cert-manager-webhook-k8s-dns-0.1.0
    release: cert-manager-webhook-k8s-dns
    heritage: Helm
spec:
  ca:
    secretName: cert-manager-webhook-k8s-dns-ca
